[tool.poetry]
description = "Generate continuous time stationary stochastic processes from a given auto correlation function."
name = "stocproc"
version = "1.1.3"
authors = ["Richard Hartmann <richard.hartmann@tu-dresden.de>"]
license = "BSD (3 clause)"
classifiers = [
"Operating System :: OS Independent",
"License :: OSI Approved :: BSD License",
"Topic :: Utilities",
"Intended Audience :: Science/Research"
]
repository = "https://github.com/cimatosa/stocproc"

[tool.poetry.dependencies]
python = "^3.9"
scipy = "^1.9.0"
fastcubicspline = "^1.1.1"
numpy = "^1.24.1"
numba = "^0.57.1"
mppfc = "^1.1.2"

[tool.poetry.dev-dependencies]
setuptools = "^59.5.0"
Cython = "^3.0.0"
black = "^23.0.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
matplotlib = "^3.6.3"
mpmath = "^1.2.1"
notebook = "^6.5.3"

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[build-system]
requires = ["poetry-core>=1.0.0", "cython", "setuptools", "numpy"]
build-backend = "poetry.core.masonry.api"
